name: Deploy Node.js Backend to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          cd homiez-backend
          npm install

      # Step 4: Build the project (if needed)
      # If you have any build process for your backend, run it here
      # Example: npm run build or any other build command.

      # Step 5: Debugging: List directory structure (Optional)
      - name: List directory structure
        run: |
          ls -al
          ls -al homiez-backend

      # Step 6: Create target directory on cPanel (if not exists)
      - name: Create backend directory on cPanel
        run: |
          ssh -o StrictHostKeyChecking=no cureojpg@$CPANEL_HOST "mkdir -p public_html/backend"

      # Step 7: Deploy to cPanel (Only Backend Folder)
      - name: Deploy to cPanel (Backend Only)
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp
          lftp -f "
          set ssl:verify-certificate no
          open ftp://$CPANEL_USER:$CPANEL_PASSWORD@$CPANEL_HOST
          mirror -R homiez-backend /public_html/backend
          quit
          "
        env:
          CPANEL_USER: ${{ secrets.CPANEL_USER }}
          CPANEL_PASSWORD: ${{ secrets.CPANEL_PASSWORD }}
          CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
