name: Deploy Node.js Backend to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the main repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Clone the homiez-backend repository
      - name: Clone homiez-backend repository
        run: |
          git clone https://github.com/E-hub-mugisha/homiez-backend.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Set up Node.js (for backend project)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 4: Install dependencies for the homiez-backend
      - name: Install dependencies
        run: |
          cd homiez-backend
          npm install

      # Step 5: Build (Optional, if needed for backend)
      - name: Build backend (if required)
        run: |
          cd homiez-backend
          npm run build

      # Step 6: Deploy to cPanel (Only Backend Folder)
      - name: Deploy to cPanel (Backend Only)
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp
          lftp -f "
          set ssl:verify-certificate no
          open ftp://$CPANEL_USER:$CPANEL_PASSWORD@$CPANEL_HOST
          mirror -R homiez-backend /public_html/backend
          quit
          "
        env:
          CPANEL_USER: ${{ secrets.CPANEL_USER }}
          CPANEL_PASSWORD: ${{ secrets.CPANEL_PASSWORD }}
          CPANEL_HOST: ${{ secrets.CPANEL_HOST }}
